/**
 * Typed API endpoint functions for Contact Form & Admin Submissions Panel.
 * Generated by: type-generator-agent
 * Source: generated-docs/specs/api-spec.yaml
 *
 * All calls go through the shared API client (@/lib/api/client).
 * DO NOT call fetch() directly in components — use these functions instead.
 */

import { get, post } from '@/lib/api/client';
import type {
  ContactSubmission,
  CreateSubmissionRequest,
  CreateSubmissionResponse,
  SessionResponse,
  SubmissionsListResponse,
} from '@/types/api-generated';

// ─── Contact Form ─────────────────────────────────────────────────────────────

/**
 * Submit a contact form (anonymous visitors).
 * POST /v1/submissions
 * Requirements: R1, R4, R5, BR1–BR5, CR5
 */
export const createSubmission = (
  data: CreateSubmissionRequest,
): Promise<CreateSubmissionResponse> =>
  post<CreateSubmissionResponse>('/v1/submissions', data);

// ─── Admin Submissions ────────────────────────────────────────────────────────

/**
 * List all contact form submissions (admin only).
 * GET /v1/submissions
 * Returns newest-first. No pagination in this version.
 * Requirements: R11, R13, R9, BR6, BR7
 */
export const listSubmissions = (): Promise<SubmissionsListResponse> =>
  get<SubmissionsListResponse>('/v1/submissions');

/**
 * Get a single submission by ID (admin only).
 * GET /v1/submissions/{submissionId}
 * Requirements: R12, R9, BR6, BR7
 */
export const getSubmission = (
  submissionId: string,
): Promise<ContactSubmission> =>
  get<ContactSubmission>(`/v1/submissions/${submissionId}`);

// ─── Authentication ───────────────────────────────────────────────────────────

/**
 * Get current session state.
 * GET /v1/auth/session
 * In NextAuth this maps to /api/auth/session.
 * Requirements: R9, R10
 */
export const getSession = (): Promise<SessionResponse> =>
  get<SessionResponse>('/v1/auth/session');
