/**
 * Generated TypeScript types from generated-docs/specs/api-spec.yaml
 * Feature: Contact Form & Admin Submissions Panel
 * Generated by: type-generator-agent
 *
 * DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec.
 */

// ─── Subject Enum ─────────────────────────────────────────────────────────────

export const SubjectOptions = [
  'General Inquiry',
  'Feedback',
  'Support',
  'Other',
] as const;

export type Subject = (typeof SubjectOptions)[number];

// ─── Error Response ───────────────────────────────────────────────────────────

/**
 * Standard API error response shape.
 * Matches: components/schemas/ErrorResponse
 */
export interface ApiErrorResponse {
  /** Human-readable error message */
  error: string;
  /** Machine-readable error code */
  code: string;
  /** Additional error details (e.g., field-level validation errors) */
  details?: string[];
}

// ─── Contact Form Submission ──────────────────────────────────────────────────

/**
 * Request body for submitting a contact form.
 * Matches: components/schemas/CreateSubmissionRequest
 * Endpoint: POST /v1/submissions
 */
export interface CreateSubmissionRequest {
  /** Submitter's full name (required — BR2) */
  name: string;
  /** Submitter's email address in user@domain.tld format (required — BR1) */
  email: string;
  /** Subject category selected from the dropdown (required — R2, BR3) */
  subject: Subject;
  /** Message body, 1–1000 characters (required — BR4, BR5) */
  message: string;
}

/**
 * Response body for a successful form submission.
 * Matches: POST /v1/submissions 201 response
 */
export interface CreateSubmissionResponse {
  /** UUID of the newly created submission */
  id: string;
  /** ISO 8601 timestamp of receipt */
  submitted_at: string;
}

/**
 * Full contact submission record (used in admin detail view).
 * Matches: components/schemas/ContactSubmission
 * Endpoint: GET /v1/submissions/{submissionId}
 */
export interface ContactSubmission {
  /** UUID of the submission */
  id: string;
  /** Submitter's full name */
  name: string;
  /** Submitter's email address */
  email: string;
  /** Selected subject category */
  subject: Subject;
  /** Full message text */
  message: string;
  /** ISO 8601 timestamp of receipt */
  submitted_at: string;
}

/**
 * Abbreviated submission for the admin inbox list cards.
 * Matches: components/schemas/SubmissionListItem
 */
export interface SubmissionListItem {
  /** UUID of the submission */
  id: string;
  /** Submitter's full name (prominent in card — R11) */
  name: string;
  /** Submitter's email address */
  email: string;
  /** Selected subject category */
  subject: Subject;
  /** Truncated message preview for card display (R11) */
  message_preview: string;
  /** ISO 8601 timestamp */
  submitted_at: string;
}

/**
 * Response from GET /v1/submissions (admin inbox).
 * Matches: components/schemas/SubmissionsListResponse
 */
export interface SubmissionsListResponse {
  /** Array of submission list items in reverse chronological order */
  submissions: SubmissionListItem[];
  /** Total count of submissions */
  total: number;
}

// ─── Authentication ───────────────────────────────────────────────────────────

/**
 * Request body for admin login.
 * Matches: components/schemas/LoginRequest
 * Note: In NextAuth, this maps to the credentials provider authorize callback.
 */
export interface LoginRequest {
  /** Admin username (seeded in config — BR6) */
  username: string;
  /** Admin password */
  password: string;
}

/**
 * Response from admin login.
 * Matches: components/schemas/LoginResponse
 */
export interface LoginResponse {
  /** Whether authentication succeeded */
  success: boolean;
  /** URL to redirect the client to after successful login (R7) */
  redirectTo?: string;
}

/**
 * Session state returned by GET /v1/auth/session.
 * null user indicates unauthenticated state.
 */
export interface SessionResponse {
  user: {
    username: string;
    role: 'admin';
  } | null;
  expires: string | null;
}
