/**
 * MSW browser worker setup for local development.
 * Generated by: mock-setup-agent
 *
 * Enables API mocking in the browser when NEXT_PUBLIC_MSW_ENABLED=true.
 * The service worker file (public/mockServiceWorker.js) must be present —
 * run `npx msw init public/` to generate it.
 *
 * This module is imported by the app's client-side initialization in dev mode only.
 */

import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

export const worker = setupWorker(...handlers);
