/**
 * Mock seed data for MSW handlers.
 * Generated by: mock-setup-agent
 * Source: generated-docs/specs/api-spec.yaml
 *
 * Provides realistic fixture data for all API endpoints.
 * Submissions are in reverse chronological order (newest first — R11).
 */

import type {
  ContactSubmission,
  SubmissionListItem,
} from '@/types/api-generated';

export const mockSubmissions: ContactSubmission[] = [
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'Jane Smith',
    email: 'jane@example.com',
    subject: 'General Inquiry',
    message:
      "Hello, I'd like to get in touch about the upcoming project. I have some questions about the timeline and deliverables. Looking forward to hearing from you.",
    submitted_at: '2026-03-04T07:02:00Z',
  },
  {
    id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    name: 'Bob Johnson',
    email: 'bob@example.com',
    subject: 'Support',
    message:
      "I'm having trouble with the onboarding process and would appreciate some guidance. The documentation seems outdated — could someone point me to the latest version?",
    submitted_at: '2026-03-03T14:15:00Z',
  },
  {
    id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    name: 'Alice Chen',
    email: 'alice.chen@example.org',
    subject: 'Feedback',
    message:
      'Just wanted to say the new interface is much cleaner. Great work on the redesign. One small suggestion: the button contrast could be improved on the settings page.',
    submitted_at: '2026-03-02T09:30:00Z',
  },
  {
    id: 'd4e5f6a7-b8c9-0123-def0-234567890123',
    name: 'Carlos Rivera',
    email: 'c.rivera@business.io',
    subject: 'Other',
    message: 'Partnership inquiry. Please check your email for details.',
    submitted_at: '2026-02-28T16:45:00Z',
  },
];

export const mockSubmissionListItems: SubmissionListItem[] =
  mockSubmissions.map((s) => ({
    id: s.id,
    name: s.name,
    email: s.email,
    subject: s.subject,
    message_preview:
      s.message.length > 80 ? `${s.message.slice(0, 80)}...` : s.message,
    submitted_at: s.submitted_at,
  }));
