/**
 * MSW request handlers for Contact Form & Admin Submissions Panel API.
 * Generated by: mock-setup-agent
 * Source: generated-docs/specs/api-spec.yaml
 *
 * Covers all endpoints defined in the OpenAPI spec:
 *   POST /v1/submissions     — createSubmission (public)
 *   GET  /v1/submissions     — listSubmissions (admin)
 *   GET  /v1/submissions/:id — getSubmission (admin)
 *   GET  /v1/auth/session    — getSession
 *
 * Base URL: http://localhost:3001/api (matches NEXT_PUBLIC_API_BASE_URL)
 */

import { http, HttpResponse } from 'msw';
import type {
  ApiErrorResponse,
  CreateSubmissionRequest,
  CreateSubmissionResponse,
  SessionResponse,
  SubmissionsListResponse,
} from '@/types/api-generated';
import { mockSubmissionListItems, mockSubmissions } from './data';

const API_BASE = 'http://localhost:3001/api';

// ─── Shared mock session state ────────────────────────────────────────────────
// Tests can override this to simulate authenticated/unauthenticated states.

let mockSessionAuthenticated = false;

/** Call in tests to simulate an authenticated admin session. */
export function setMockSessionAuthenticated(value: boolean): void {
  mockSessionAuthenticated = value;
}

// ─── Handlers ─────────────────────────────────────────────────────────────────

export const handlers = [
  /**
   * POST /v1/submissions
   * Submit a contact form (anonymous visitors).
   * Happy path: returns 201 with id and submitted_at.
   */
  http.post<Record<string, never>, CreateSubmissionRequest>(
    `${API_BASE}/v1/submissions`,
    async ({ request }) => {
      const body = await request.json();

      // Basic server-side validation (mirrors BR1–BR5)
      const errors: string[] = [];

      if (!body.name || body.name.trim() === '') {
        errors.push('Name is required.');
      }
      if (!body.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(body.email)) {
        errors.push('Please enter a valid email address.');
      }
      if (
        !body.subject ||
        !['General Inquiry', 'Feedback', 'Support', 'Other'].includes(
          body.subject,
        )
      ) {
        errors.push('Subject is required.');
      }
      if (!body.message || body.message.trim() === '') {
        errors.push('Message is required.');
      } else if (body.message.length > 1000) {
        errors.push('Message must be 1,000 characters or fewer.');
      }

      if (errors.length > 0) {
        return HttpResponse.json<ApiErrorResponse>(
          {
            error: 'Validation failed',
            code: 'VALIDATION_ERROR',
            details: errors,
          },
          { status: 400 },
        );
      }

      const response: CreateSubmissionResponse = {
        id: 'mock-' + Math.random().toString(36).slice(2, 10),
        submitted_at: new Date().toISOString(),
      };

      return HttpResponse.json(response, { status: 201 });
    },
  ),

  /**
   * GET /v1/submissions
   * List all submissions (admin only).
   * Returns 401 if not authenticated.
   */
  http.get(`${API_BASE}/v1/submissions`, () => {
    if (!mockSessionAuthenticated) {
      return HttpResponse.json<ApiErrorResponse>(
        {
          error: 'Authentication required',
          code: 'UNAUTHENTICATED',
        },
        { status: 401 },
      );
    }

    const response: SubmissionsListResponse = {
      submissions: mockSubmissionListItems,
      total: mockSubmissionListItems.length,
    };

    return HttpResponse.json(response, { status: 200 });
  }),

  /**
   * GET /v1/submissions/:submissionId
   * Get a single submission by ID (admin only).
   * Returns 401 if not authenticated, 404 if not found.
   */
  http.get(`${API_BASE}/v1/submissions/:submissionId`, ({ params }) => {
    if (!mockSessionAuthenticated) {
      return HttpResponse.json<ApiErrorResponse>(
        {
          error: 'Authentication required',
          code: 'UNAUTHENTICATED',
        },
        { status: 401 },
      );
    }

    const submission = mockSubmissions.find(
      (s) => s.id === params.submissionId,
    );

    if (!submission) {
      return HttpResponse.json<ApiErrorResponse>(
        {
          error: 'Submission not found',
          code: 'NOT_FOUND',
        },
        { status: 404 },
      );
    }

    return HttpResponse.json(submission, { status: 200 });
  }),

  /**
   * GET /v1/auth/session
   * Returns current session state.
   * Maps to NextAuth's /api/auth/session in practice.
   */
  http.get(`${API_BASE}/v1/auth/session`, () => {
    const response: SessionResponse = mockSessionAuthenticated
      ? {
          user: { username: 'admin', role: 'admin' },
          expires: new Date(
            Date.now() + 30 * 24 * 60 * 60 * 1000,
          ).toISOString(),
        }
      : {
          user: null,
          expires: null,
        };

    return HttpResponse.json(response, { status: 200 });
  }),
];
