/**
 * MSW server setup for Node.js test environment (Vitest / jsdom).
 * Generated by: mock-setup-agent
 *
 * Usage in tests:
 *
 *   import { server } from '@/mocks/server';
 *   import { http, HttpResponse } from 'msw';
 *
 *   // Override a handler for a specific test:
 *   server.use(
 *     http.post('http://localhost:3001/api/v1/submissions', () =>
 *       HttpResponse.json({ error: 'Internal server error', code: 'INTERNAL_ERROR' }, { status: 500 })
 *     )
 *   );
 *
 * The server is started/stopped automatically via vitest.setup.ts.
 */

import { setupServer } from 'msw/node';
import { handlers } from './handlers';

export const server = setupServer(...handlers);
